\section*{- 研究振告 -}

\title{
植物激素与金属离子对稻种萌发影响的热动力学研究
}

\author{
周培疆 " 胡云楚 … 谢昌礼 宋昭华 汪存信 屈松生
}
（武双大学化学系。武没 430072）
周涵蹈 朱英国 舒理㯖
（武汉大学生命种学学院，武汉 430072）

\begin{abstract}
摘 要
![](./images/ca18d8f0d75b425b71f067873a5bb6fb_1002_1055_327_1658.jpg)
![](./images/ca18d8f0d75b425b71f067873a5bb6fb_1053_1098_264_1658.jpg)育稻种在不同介质中萌发生长动力学数，建立了相应的动力学经验武。并进一步探讨了激动素（KT）和生长来（IAA）及 \(\mathrm{Zn}^{2+}\) 和 \(\mathrm{Cu}^{2+}\) 对稻种荷发过程的影响。
\end{abstract}

关链词 稻种萌发，植物激素，金属离子，微量热法，热动力学

植物激素和金属离子对植物生长发育的影响已有较多研究 \({ }^{[1 \sim 4]}\) ，但未见有关于果微量热法和热动力学方法研究植物激素和金属离子对移种萌发影响的报道。我们用自研制的微热量计测定了杂交水稻新品种马协雄性不育系稻种在植物激素和金属离子介质中萌发热功率一时间冊线，从而获得了该稻种在不同介质中萌发各产热阶段的热数据。计算了马协雄生不育系稻种在不同介质中荷发生长动力学参数，建立了相应的动力学经验式。并进一步探讨了激动素和生长素及 \(\mathrm{Zn}^{2+}\) 和 \(\mathrm{Cu}^{2+}\) 对稻种萌发过程的影响。研究结果表明，激动素和金属离子对稻种萌发有明显的加速作用，而生长素对稻种萌发则有一定的抑制作用。

\section*{1 材料和方法}

马协雄性不育系杂交稻种由武汉大学生命科学学院遗传研究所提供。
\(1 \times 10^{-8} \mathrm{~mol} \mathrm{~L}^{-1} \mathrm{KT}, \mathrm{IAA}, \mathrm{Zn}\left(\mathrm{NO}_{3}\right)_{2}, \mathrm{Cu}\left(\mathrm{NO}_{3}\right)_{2}\) 溶液为生化和分析纯试剂，用二次蒸馏水配制。
实验用自研制热导式微热量计本体结构和性能指标见文献[5]。
选取 20 粒（约 0.5 g ）稻种，肧位朝上置于特制加样器上息于测量池中。佰温 10 h 待基线平稳后将稻种与事先移入的 3 ml 介质接触，用 YEW-3066 型记录仪连续记录 \(25^{\circ} \mathrm{C}\) 、适量通大气及无光照条件下稻种晿发热功率-时间曲线，其它实验条件同前报 \({ }^{[8]}\) 。

\section*{2 结果与讨论}

\section*{2.1 稻种在不同介质中萌发热功目-时间曲线}

实验测定的稻种在不同介质中萌发热功率-时间曲线示于图1和图2。实验结果表明，尽管实验用稻种和介质等与前报有所不同，但其药发热功率-时间曲线形状则基本相同 \({ }^{[6]}\) 。稻种萌发不论在何介质中进行都要经过三个
![](./images/ca18d8f0d75b425b71f067873a5bb6fb_2115_2166_203_1719.jpg)果可以看出，䄸种在纯水、植物激素和 \(\left.\mathrm{Zn}^{-1} \mathrm{NO}_{3}\right)_{2}\) 介质中萌发热功率-时间曲线及其铣征值相近。而在 \(\mathrm{Cu}\left(\mathrm{NO}_{3}\right)_{2}\)介质中稻种萌发的活化期（ \(\mathrm{t}_{\mathrm{B}}\) ）显著缩短，生长阶段明显提前。这可能与 \(\mathrm{Cu}^{2+}\) 能激活种内某些氧化酶促进稻种在砎发过程中的呼吸作用有关 \({ }^{[4]}\) 。

\footnotetext{
* 国家自然科学基金究助项目 \(*\) * 通信联系人 \(* * *\) 中南标学院访问学者。株州421006
}
![](./images/061c35366c08ac7341123a3037149c0b_397_1011_213_873.jpg)

图1 稻种在纯水中的萌发热功率-时间曲线
表1 稻种在不同介质中萌发热功率-时间曲线特性值。（25 C）
\begin{tabular}{|c|c|c|c|}
\hline 介质 & 漫透阶段（A）
\[
\mathbf{P}_{\max } / \mu \mathbf{W}
\] & 活化阶段 (B) \(t_{B} / h\) & 生长阶段（C） ic, o/h \\
\hline \(\mathrm{H}_{2} \mathrm{O}\) & 110 & 14 & 16 in \\
\hline KT & 140 & 17 & 18th \\
\hline IAA & 120 & 14 & 16th \\
\hline \(\mathrm{Zn}\left(\mathrm{NO}_{3}\right)_{2}\) & 100 & 16 & 18th \\
\hline \(\mathrm{Cu}\left(\mathrm{NO}_{3}\right)_{2}\) & 70 & 5 & 6th \\
\hline
\end{tabular}
![](./images/061c35366c08ac7341123a3037149c0b_354_1033_936_1636.jpg)
![](./images/061c35366c08ac7341123a3037149c0b_1040_1080_933_1695.jpg)
![](./images/061c35366c08ac7341123a3037149c0b_1074_1108_1022_1493.jpg)

\section*{2.2 榣种在不同介质中前发焉㘫热动力学}

从图1和图2可知，䄸种在不同介质中萌发生长阶段热功率一时间曲线均呈 \(S\) 型。可用式 \(P_{i}=p o /\) \([s+(1-s) \exp (-k t)]\) 或 \(\ln \left[\left(a / p_{0}\right)-1\right]=\ln [6-\)
![](./images/061c35366c08ac7341123a3037149c0b_1304_1346_1007_1699.jpg)常敏： s 是生长抑制性因子， p ；表示时间 t 时稻种萌发热功率。 \(\beta\) 是衰政速率常数（ \(\beta=\mathrm{sk}\) ）。式中 \(\mathrm{a}=\mathrm{po} /\)
![](./images/061c35366c08ac7341123a3037149c0b_1445_1485_1010_1697.jpg)䊅觜种明发生长阶段热功率-时间曲线上的 \(\mathrm{p}_{\mathrm{t}}\) 和相对时间：值代入上式。在计算中选定适宜 a 值便式
（8）线性最佳便可求得 \(\mathbf{k} 、 \mathbf{s}, \beta\) 和 po。实验测定值与动力学参数计算值份别列于表2和表3。
![](./images/061c35366c08ac7341123a3037149c0b_1632_1672_423_1463.jpg)
\begin{tabular}{|c|c|c|c|c|c|c|c|c|c|c|}
\hline & t/h & 6 & 12 & 18 & 24 & 30 & 36 & 42 & 48 & 54 \\
\hline \multirow{5}{*}{p. \(/ \mu \mathrm{W}\)} & \(\mathrm{H}_{2} \mathrm{O}\) & 90 & 200 & 330 & 450 & 5.10 & 700 & 820 & 940 & 1050 \\
\hline & KT & 60 & 220 & 360 & 500 & 345 & 790 & 910 & 1020 & 1120 \\
\hline & IAA & 130 & 280 & 410 & 560 & 739 & 840 & 980 & \(1 \times 100\) & 1200 \\
\hline & \(\mathrm{Zn}\left(\mathrm{NO}_{3}\right)_{2}\) & 80 & 180 & 320 & 450 & \(50 \%\) & 2.70 & 770 & 880 & 940 \\
\hline & \(\mathrm{Cu}\left(\mathrm{NO}_{3}\right)_{2}\) & 120 & 280 & 460 & 700 & 95 & 1130 & 1300 & 1480 & 1630 \\
\hline
\end{tabular}
![](./images/061c35366c08ac7341123a3037149c0b_1996_2036_570_1321.jpg)
\begin{tabular}{|c|c|c|c|c|c|}
\hline 介质 & \(\mathrm{k} / \mathrm{h}^{-1}\) & s & fix-: & poluty & I \\
\hline \(\mathrm{H}_{2} \mathrm{O}\) & 0. 1055 & 0.06182 & 0.196525 & 59.2 & -0.9943 \\
\hline KT & 0. 1327 & 0.04025 & 0.005341 & 39.5 & \(-0.9893\) \\
\hline IAA & 0. 1013 & 0.07660 & 0. 0.07759 & 87.4 & -0.9959 \\
\hline \(\mathrm{Zn}\left(\mathrm{NO}_{3}\right)_{2}\) & 0.1188 & 0.05640 & 0. 1906702 & 48.0 & -0.996.3 \\
\hline \(\mathrm{Cu}\left(\mathrm{NO}_{3}\right)_{2}\) & 0.1168 & 0.04863 & 0.005680 & 71.8 & \(-0.9972\) \\
\hline
\end{tabular}

相应的马协雄性不育系稻种在不同介质中葫发生长动力学经验式如下：
\begin{tabular}{ll}
\(\mathrm{H}_{2} \mathrm{O}:\) & \(p_{1}=59.2 /[0.06182+0.9382 \exp (-0.1055 \mathrm{t}) \mathrm{t} \leqslant 54 \mathrm{~h}\) \\
\(\mathrm{KT} ;\) & \(p_{\mathrm{t}}=39.5 /[0.04025+0.9598 \exp (-0.1327 \mathrm{t}) \mathrm{t} \leqslant 54 \mathrm{~h}\) \\
\(\mathbb{1 A A}:\) & \(p_{1}=87.0 /[0.07650+0.9234 \exp (-0.1013 \mathrm{t}) \mathrm{t} \leqslant 54 \mathrm{~h}\) \\
\(\mathrm{Zn}\left(\mathrm{NO}_{3}\right)_{2}\) & \(p_{1}=48.0 /[0.05640+0.9436 \exp (-0.1188 \mathrm{t}) \mathrm{t} \leqslant 54 \mathrm{~h}\) \\
\(\mathrm{Cu}\left(\mathrm{NO}_{3}\right)_{2}\) & \(p_{1}=71.8 /[0.04863+0.9514 \exp (-0.1168 \mathrm{t}) \mathrm{t} \leqslant 54 \mathrm{~h}\)
\end{tabular}
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_577_628_229_1693.jpg)它长速率常数均天于它拄水中的生长速率常数，而它在这些介质中的生长抑制性因子均小于它在水中的生长抑
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_668_724_168_1697.jpg)
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_719_767_168_1697.jpg)
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_766_814_172_1698.jpg)定的 \({ }^{[7]}\) 。

用溦量热及熟动力学方法研究晏神因素对种子萠发的影响，为种子科学和技术的研究开辟了一个新的途径，
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_906_954_167_1392.jpg)

\section*{参考文献}

1 A. A bhan. S. Prusinaki. Kinetin entanced aminovylopropane-1-carboxylic avid atilization during alleviation of high temper-
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_1046_1089_210_902.jpg)
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_1083_1136_168_1375.jpg)
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_1132_1180_168_1401.jpg)
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_1174_1227_167_1698.jpg) ommun Son Sci Pl Áral, 1980. T1. 1851
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_1261_1306_168_1697.jpg) . 1993.5. 61
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_1344_1389_170_1399.jpg)
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_1391_1436_171_1159.jpg)

\title{
Studies on Tharmektics for Effects of Phytohormones and metallic loms on the Germathation of the Rice Seed
}

\author{
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_1675_1718_349_1521.jpg) \\ ( Weparcuevir of Chemistry, Whan Gniversity, Wuhan 430072) \\ ![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_1807_1855_644_1221.jpg) \\ (School of Eife Science, Wuhan Universiry, Wuhan 430072)
}

\begin{abstract}
Abservart
The thermal powet-tinne curges of the germination of the sed for the male sterile line of Maxie rice in the mediators of phytohgmanes and metalic ions have been etetermined by using a microcalorimeter set up by ourselves. The results obtained from these curves in different thermogenesising stapes for the rice seed have been sudied. Sonne thermokinetic parameters for the germination the rice seed in different mediators and the corresponding experimental thermokinetic equations have been talculated and established. The effects of kinelin (KT) and auxin( AA ) as well as \(2 \mathrm{~m}^{2+}\) and \(\mathrm{Cu}^{i+}\) on the process of the germination of the rice seed have been compared and discussed.
\end{abstract}
![](./images/6f91153f0fb93ee7cad625f4d8b38c5d_2330_2377_231_1541.jpg)