\title{
论种子鉴定与种子质量管理的关系
}

王彦荣
（甘肃草原生态研究所 农业部牧草种子检验中心兰州，730020）

\section*{提 要}

通过对种于鉴定的内容、伓节及一般原则的阐述，分析了种子鉴定在种子生产和市场中的作用，论述了种子鉴定与种子质量营理包括种子检脸和种子立法等的关系，认为建主种子鉴定体来是完善我国种子质量管理体来和拱高种子貭量的当务之急。

\section*{1 引 茟}

种子质量管理通常是指政府部门对种子培育、生产和市场等活动进行监督、管理，以保证获得优质种子。其管理的目的是为了保护农业（或草业）生产和生产者的利益，以免在生产过程中由于播种用种质量低劣而造成损失。种子质量管理涉及到种子工作的各有关部门，是由诸多相关的要素和环节构成的一项系统工程。世界著名种子学家 J.E. Douglas 先生（1980）曾指出，为了保证获得优质的种子，一个国家或政府通常采取三种措施进行种子质量管理，即种子鉴定、种子检验和种子立法。可见种子监定是种子质量管理的三要索之一。我国自 80 年代以来，先后建立了农业部部属和省属种子质检中心（站）数十个，1989年加入了国际种子检验协会，1994 年咸立了全国农业质量监督管理信息网农牧渔业种子种苗协作组，一个较完善的种子检验体系已形成。另外，国务院 1989 年颁布了《中华人民共和国种子管理条例》，农业部于1991年颁布了《中华人民共和国种子管理条例农作物种子实施细则》，许多省也相继制定了本省种子管理办法等，种子质量管理已有法可依，有章可循。然而近年来我国种子质量问题却频频出现，据国家技术监督局 1994 年组织的第一季度农资产品的监督抽査结果表明，抽査的7省89个经销单位的 156 个玉米、棉花种子样品，合格率仅为 \(19.2 \%\) ，抽查的 108 份玉米种子中，纯度合格率为 \(2.8 \%\) （张双武，1995），种子质量之低令人震惊。另外，一件件以次充好，以假乱真的种子案例也连连发生，给农业生产造成的损失，令人蜰目惊心。究其这些问题的原因，一方面与种子管理有法不依、执法不严有关，另

一方面与我国的种子质量管理体系尚不健全，尤其是缺乏种子鉴定体系有关。本文拟通过分析种子鉴定的内容、环节及一般原则等，以阐述种子鉴定与种子质量管理的关系，旨在为如何健全我国质量管理体系提供一孔え见。
2 种子监定的内容、环节及一般原则 根据国际经济联合与发展组织（OECD, 1995）以及大多数发达国家关于种子鉴定方案的内容、种子鉴定（英文： Seed certification）就是对农业生产中所采用的优良品种在世代繁殖过程中进行品种真实性和品种纯度检验，以确保种质质量和保护使用者利益。品种真实性往往指一批种子所属品种、种或属与标签上的标明是否相同，是否名副其实。品种纯度是指供检样品中本品种的种子数（或株数）占供检样品总数的百分率。

种子鉴定在大多数国家是由官方组织进行的。经鉴定合格的种批系（貼）有官方的标签，以使农民和购买者确认和了解播种材料。

种子鉴定是种子质量管理体系的一个子系统，由若干个密切相关的要素构成。其中，品种审定、考证种子的来源、田间检验、扞样、室内检验、加标签以及建立品种以对照小区等构成了该系统的主要环节和内容，现分述如下：
2.1 品种审定 是由国家专职机构如品种审定委员会等负责，对来源于国家植物育种机构、地方单位或国外柇进的新品种，在全国不同地区、不同生态采件下进行试种，评定其作为新品种的合格性。审定的主要内容包括（1）品种的三性即独特性（distinct）、均一性（uniform）和稳定性（stable），（2）品种的种植与利用价值，如品种的抗性、产量及有关农艺特性等。经审定合格的品种方可作为新品种进行登记，列入国家品种审定目录，进而用于种子等殖和农业生产。同时官方对新品种的形态特性等进行详细登记，以作为该品种在繁殖过程种子监定的基本依据。品种审定可以由独立于种子鉴定的部门来完成，也可以作为种子鉴定的一个环节，由种子鉴定部门完成，这可视管理上的方便而定。
2.2. 考证种的来滈 在播种前, 应对种子来源进行考证。考证的办法是检査种子所符标签文件等是否符合作为播种材料的要求。另外，在先进的种子鉴定体系有时也进行扞样、空内检验和进行小区对照检验等，以确保种子的真实性和纯度。在种子鉴定中往往对不同繁殖代的种子有不同的命名，以便于区分。如 OECD 品种审定方案中将种子分为前基础种子、基础种子、认可一代种子、认可二代种子和认可三代种子或多代种子等。一般只要经鉴定证明种子来源和品种纯度是合格

的，至于认可种子的繁殖代数是不受限制的。增加等殖代数，可扩大认可种子的数量，并减少对前基础种子的需求。但是，对那些异花授粉和植物因其生物学原因。往往需限制㧘殖代数。
2.3 田间检婴会 由专职人员在作物生育期间，到种子繁殖地或留种田进行取样、分析、鉴定。其主要项目是种子的真实性和品种纯度。此外，还需了解田间杂草、病虫感梊程度、生育情况、前作种类、隔离情况和倒伏程度等。检验后填写田间检验报告书，确定该田块能否作为种子田，并提出处理意见。田间检验细则可参见 OECD 的各类种子的田间检验指南（OECD，1995）等。
2.4 扞样 由专职扞样员对自合格的种子田收获、加工过的种子进行扞样，扞样方法应按《国际检验规程》 （ISTA，1993）或本国《种子敛验规程》进行。对扞过样的种批要进行封线。
2.5 室内检验 . 由专职检验员依据《国际种子检验规程》或本国《种子检验规程》，采用形态或生化等方法测定品种纯度，并出据检验报告。有时亦根据需要进行质量定级。
2.6 田间小区对照捡验 在种子熬殖的任一阶段，如发生品种混杂，育种家经过多年辛勤培育出的品种就可以迅速丢失。许多先进的种子方案都包括建立专门的田间品种检验小区，用于大田种子生产中同品种的纯度辅助鉴定，例如 OECD 方案（OECD，1995）以及丹麦等国的种于质量管理体系（王彦荣，1995）等，主要做法是将待鉴品种的样品与相同品种的标样（一般来源于育种者提供的基础种子）邻区播种，在植株最能表现其品种特性的生长时期，进行对比纯度测定。田间小区对照检验分为前对照检验和后对照检验两种，前者为在播前或播期对播种种子进行扞样检验，而后者是对收获清选后的种批扞样检验。
2.7 加标签 经上述一系列检验达到一定质量标准的种批，应由官方人员在种批内各容器或种子袋上加标签，以作为种子质量的证件。OECD 对不同世代种子的标签有不同颜色的要求，例如，前基础种子、基础种子、认可一代、认可二代的种子标签分别为白色加一条紫色、白色、蓝色和红色等。另外，对标签的尺寸、材料、内容和文字等亦有统一的规定。农民或购买者可根据标签一目了然地挙握播种材料。

\section*{3 种子鉴定与种子质穓管理的关系}

综上分析，种子鉴定是种子定量管理的重要内容，是整个种子管理体系中不可缺少的一部分，没有种子监定体制或体制不健全，品种纯度就难以保证，那么靠优良品种增产就可能成为一种富目甚至冒险的活动，

就有可能出现"种禾谷不出穂"，甚至出现"种瓜得互"的现象。

种子鉴定是政府部门监督管理种子生产和种子市场的一种手段，为了保证其公证性和权威性，前者必须在机构设置上完全独立于后二者。但是种子鉴定是种子生产和经营活动的催化剂，若达不到并存和催化的作用，也就失去了种子鉴定工作的目的。其相互关系见图。
![](./images/70897ef15049194f69c4c31399954111_722_1330_911_1692.jpg)

种子监定与种子生产和市场的关系
种子鉴定与种子检验（Seed testing）有着一定的联系，但二者不能相互替代。种子鉴定是侧重于品种纯度和品种真实珄测定，在鉴定中多以田间为场所，依据植株形态鉴定。而种子检验主要是测定种子的播种或这藏质量，如：发芽、净度、水分、活力和健康状况等，是在室内依据种子生理特性和形态特性等测定。尽管二者在扞样、室内品种测定等方面联系密切，但检验场所与技术上差别很大，所以在大多数国家都形成了并行的二个体系。

种子鉴定是种子立法的条件，从䢍辑上讲应先有种子鉴定（包括品种审定）、种子检验、种子市场等体系，方可谈种子立法（Douglas 1980）。否则立法便可能成为无源之水，无本之木。

我国虽然已建立了种子检验体系和颁布了《种子管理》条例，但是尚未建立起种子鉴定体系，这是导致。种子质量问题不断出现的主要原因之一。为此，笔者认为建立种子鉴定体系是完善我国种子质量管理体系和提高种子质量管理水平的当务之急，是解决种子质量问题的一项"亡羊补牢"的措施，望尽快引起各有关部门的重视。
（手考文献略）